#!/usr/bin/env bash

# use ../../scripts/bash/gcloud_odm_800nm_vc

# the purpose of this script is produce orthomosaic photos using opendronemap on gcloud

# the steps of this process are:

echo " "
echo "*****begin stitching 800nm*****"
echo " "

# 1. start the gcloud instance

gcloud compute instances start ianm800nm --zone us-east4-a --quiet
gcloud compute ssh ianm800nm --zone us-east4-a --command "rm -rf /home/ianmcnish/*"

# 2. copy the ground control point data and photos to the gcloud instance

gcloud compute scp gcp_lists/800nm_gcp_list.txt ianm800nm:~/ --zone us-east4-a
gcloud compute scp 800nm_autoexposure_calibration/*.jpg ianm800nm:~/ --zone us-east4-a

# 3. execute opendronemap

gcloud compute ssh ianm800nm --zone us-east4-a --command "docker run -i -v /home/ianmcnish/800nm_gcp_list.txt:/code/images/800nm_gcp_list.txt -v /home/ianmcnish/:/code/images -v /home/ianmcnish/:/code/odm_orthophoto -v /home/ianmcnish/:/code/odm_texturing opendronemap/opendronemap:0.4.0 --gcp /code/images/800nm_gcp_list.txt --fast-orthophoto"

# 4. delete original image files and transfer the results to computer

gcloud compute ssh ianm800nm --zone us-east4-a --command "rm /home/ianmcnish/calibrated*"
rm -rf 800nm_orthophoto/
mkdir 800nm_orthophoto/
gcloud compute scp ianm800nm:/home/ianmcnish/* 800nm_orthophoto/  --zone us-east4-a

# 5. delete remaining files

gcloud compute ssh ianm800nm --zone us-east4-a --command "rm -r /home/ianmcnish/*"

# 6. stop docker on gcloud instance

#gcloud compute ssh ianm800nm --zone us-east4-a --command "docker stop $(docker ps -a -q)"

# 7. delete files from docker

#gcloud compute ssh ianm800nm --zone us-east4-a --command "docker rm $(docker ps -a -q)"

# 8. stop the glcoud instance

gcloud compute instances stop ianm800nm --zone us-east4-a --quiet

# 9. convert orthomosaic format

echo " "
echo "*****finish stitching 800nm*****"
echo " "
